services:
  maven-builder:
    image: maven:3-openjdk-17
    container_name: maven_builder
    working_dir: /app
    volumes:
      - .:/app
    command: ["mvn", "clean", "package", "-DskipTests"]

  postgres:
    image: postgres:13
    container_name: sellingcourse_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: DatabaseCourse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sellingcourse_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sellingcourse_app
    depends_on:
      maven-builder:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/DatabaseCourse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./src/main/java/org/example/sellingcourese/video:/app/video
      - ./target:/app/target
    networks:
      - sellingcourse_network

volumes:
  postgres_data:

networks:
  sellingcourse_network:
    driver: bridge
